databases:
  - name: ds_vendas
    databaseName: ds_vendas
    user: admin

services:
  - type: web
    name: adote
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn adote.wsgi:application"
    envVars:
      - key: postgres://admin:JskMH1Mgrv9ubLQyn92uGO8FmLIGIuC9@dpg-cetcmfpa6gdut0opk240-a/ds_vendas
        fromDatabase:
          name: adote
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4